---
# tasks file for MySql
- name: Install mysql
  apt:
    pkg: mysql-server
    state: present

- name: Copy all files
  copy:
    src: "{{ item }}"
    dest: ~/
    mode: 0700
  with_fileglob:
    - files/joomla.sh
    - files/joomla.sql

- name: Create DB and privileges for Joomla user
  command: ~root/joomla.sh
