---
- hosts: joomla1 joomla2
  become: true

  roles:
    - common

- hosts: joomla-db
  become: true

  roles:
    - common
    - MySql

- hosts: joomla-lb
  become: true

  roles:
    - common
    - haproxy
  vars:
    haproxy_app_name: joomla
    haproxy_enable_stats: false
    haproxy_backend_servers:
      - {name: joomla1, ip: 192.168.100.11, port: 80, paramstring: cookie A check}
      - {name: joomla2, ip: 192.168.100.12, port: 80, paramstring: cookie A check}
